// New code, MPL-2.0. Shared, unchanged final-tail gate used before arithmetic.
#pragma once
#include "inference_core.h"
#include "final_import_tail_audit.h"
namespace chandra::dc::inference {
inline void requireCleanFinalImportForArithmetic(const import_row::FinalTailObserver& observer,WeightImportAPI api,bool referencesReleased){
 require(api==WeightImportAPI::defaultInitial&&observer.weightSrvOnly(),"Arithmetic blocked: DEFAULT initial read-only weights required");
 const auto state=observer.report();const auto& c=state.at("counts");
 auto boolean=[](const Json& value,bool wanted){return value.is_boolean()&&value.get<bool>()==wanted;};
 auto number=[](const Json& value,uint64_t wanted){return value.is_number_unsigned()&&value.get<uint64_t>()==wanted;};
 auto zero=[](const Json& value){return value.is_number_integer()&&value==0;};
 require(observer.completed()&&state.at("schema")=="chandra.directcompute.final-import-tail-audit.v1"&&state.at("weight_import_api")==weight_import::name(api)&&state.at("D3D11_usage")=="DEFAULT"&&state.at("outcome")=="all_selected_tails_match"&&
  boolean(state.at("complete"),true)&&boolean(state.at("selected_tails_match"),true)&&boolean(state.at("constructor_return_observed"),true)&&boolean(state.at("same_original_embedding_head_Storage_checked"),true)&&boolean(state.at("target_references_released"),referencesReleased)&&
  boolean(state.at("source_raw_written_and_flushed"),true)&&number(state.at("source_payload_bytes"),import_row::final_tails::rowArrayBytes)&&boolean(state.at("matched_prefix_raw_written_and_flushed"),true)&&number(state.at("matched_prefix_payload_bytes"),import_row::final_tails::rowArrayBytes)&&
  boolean(state.at("first_bad_raw_write_attempted"),false)&&boolean(state.at("first_bad_raw_written_and_flushed"),false)&&state.at("first_bad").is_null()&&state.at("first_refusal").is_null()&&
  boolean(state.at("journal_write_failed_or_torn"),false)&&boolean(state.at("failure_evidence_persistence_failed"),false)&&number(state.at("journal_records_written"),22)&&number(state.at("journal_write_attempts"),22)&&zero(state.at("early_GPU_observations"))&&boolean(state.at("request_replayed"),false),
  "Arithmetic blocked: complete persisted ten-tail equality and constructor return required");
 for(const char* key:{"API_operations_admitted","API_calls_admitted","API_operations_returned","original_drains_completed"})require(number(c.at(key),732),"Arithmetic blocked: complete original 732 API operations/returns/drains required");
 require(number(c.at("completed_storage_bytes"),9078531072ull)&&boolean(c.at("API_operation_pending"),false)&&boolean(c.at("direct_comparison_pending"),false),"Arithmetic blocked: incomplete original import extent or pending operation");
 for(const char* key:{"CPU_source_snapshots_completed","direct_read_call_admissions","direct_read_returns_observed","copies_submitted_observed","completed_samples","matched_prefix_rows"})require(number(c.at(key),10),"Arithmetic blocked: ten completed source/copy/equality observations required");
 const bool initial=api==WeightImportAPI::defaultInitial;
 require(number(c.at("Device_upload_UpdateSubresource_admissions"),initial?0:732)&&number(c.at("UpdateSubresource_returns_observed"),initial?0:732)&&number(c.at("DEFAULT_initial_data_Device_create_admissions"),initial?732:0)&&number(c.at("DEFAULT_initial_data_Device_create_returns"),initial?732:0),"Arithmetic blocked: API-specific admission/return counts differ");
 const auto& srv=state.at("weight_srv_only");require(srv.at("contract")==import_row::FinalTailObserver::forecast(api,true).at("weight_srv_only")&&number(srv.at("descriptors_checked"),732)&&boolean(srv.at("all_returned_descriptors_checked"),true),"Arithmetic blocked: all actual DEFAULT raw SRV/no-UAV descriptors required");
 const auto& creation=srv.at("selected_target_creation_descriptors");require(creation.is_array()&&creation.size()==10,"Arithmetic blocked: ten actual selected creation descriptors required");
 for(uint32_t i=0;i<10;++i){const auto target=import_row::tails::target(i);const auto& receipt=creation.at(i);const auto& descriptor=receipt.at("descriptor");
  require(number(receipt.at("operation_ordinal"),i+1)&&receipt.at("tensor_name")=="model.language_model.embed_tokens.weight"&&number(receipt.at("chunk_index"),i)&&number(descriptor.at("ByteWidth"),target.bytes)&&number(descriptor.at("SRV_NumElements"),target.words)&&
   number(descriptor.at("Usage"),weight_srv_only::defaultUsage)&&number(descriptor.at("BindFlags"),weight_srv_only::shaderResourceBind)&&number(descriptor.at("MiscFlags"),weight_srv_only::rawMisc)&&number(descriptor.at("CPUAccessFlags"),0)&&number(descriptor.at("StructureByteStride"),0)&&number(descriptor.at("SRV_Format"),weight_srv_only::rawFormat)&&number(descriptor.at("SRV_ViewDimension"),weight_srv_only::bufferExDimension)&&number(descriptor.at("SRV_FirstElement"),0)&&number(descriptor.at("SRV_Flags"),weight_srv_only::rawSRVFlag)&&boolean(descriptor.at("readonly_weight"),true)&&boolean(descriptor.at("SRV_present"),true)&&boolean(descriptor.at("UAV_present"),false)&&boolean(descriptor.at("SRV_same_resource"),true),"Arithmetic blocked: selected actual read-only weight creation identity differs");
 }
 const auto& sources=state.at("source_records");const auto& samples=state.at("post_import_samples");require(sources.is_array()&&samples.is_array()&&sources.size()==10&&samples.size()==10,"Arithmetic blocked: complete ordered source/sample arrays required");
 for(uint32_t i=0;i<10;++i){const auto target=import_row::tails::target(i);const auto& source=sources.at(i);const auto& sample=samples.at(i);
  require(number(source.at("shard_index"),i)&&number(source.at("global_row"),target.row)&&number(source.at("row_bytes"),import_row::tails::rowBytes)&&number(source.at("source_payload_offset"),uint64_t(i)*import_row::tails::rowBytes)&&boolean(source.at("copied_from_actual_submission_pointer"),true)&&boolean(source.at("source_view_alive_at_snapshot"),true)&&
   number(sample.at("shard_index"),i)&&number(sample.at("global_row"),target.row)&&number(sample.at("matched_prefix_payload_offset"),uint64_t(i)*import_row::tails::rowBytes)&&boolean(sample.at("byte_equal_to_actual_API_source"),true)&&sample.at("phase")=="after_full_import_constructor_return_before_arithmetic"&&
   source.at("sha256").is_string()&&source.at("sha256").get<std::string>().size()==64&&sample.at("source_sha256")==source.at("sha256")&&sample.at("direct_sha256")==source.at("sha256"),"Arithmetic blocked: source/sample identity or byte-equality record differs");
 }
 const auto& transport=state.at("last_transport");const auto& sourceDescriptor=transport.at("source_descriptor");require(number(sourceDescriptor.at("usage"),weight_srv_only::defaultUsage)&&number(sourceDescriptor.at("bind_flags"),weight_srv_only::shaderResourceBind)&&number(sourceDescriptor.at("misc_flags"),weight_srv_only::rawMisc)&&number(sourceDescriptor.at("cpu_access_flags"),0)&&number(sourceDescriptor.at("structure_byte_stride"),0),"Arithmetic blocked: last direct transport source descriptor differs");require(number(transport.at("copies_submitted"),1)&&boolean(transport.at("before_copy_drain_completed"),true)&&boolean(transport.at("after_copy_drain_completed"),true)&&boolean(transport.at("staging_created"),true)&&boolean(transport.at("staging_released"),true)&&boolean(transport.at("map_attempted"),true)&&boolean(transport.at("map_copied"),true)&&boolean(transport.at("unmapped"),true)&&boolean(transport.at("copy_resubmitted"),false),"Arithmetic blocked: completed original direct-copy transport required");
}
} // namespace chandra::dc::inference
